language: python

python:
  - 3.10-dev

install:
  - make init
  - pip install --user codecov
  - pip install --user coveralls

script:
  - make test

after_success:
  - codecov
  - coverage run --source=pystr -m pytest tests/*
  - coveralls
