#!/usr/bin/env python3

from pystr.trie import depth_first_trie
import sys

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(f"{sys.argv[0]} needs string arguments to build the trie from.")
        sys.exit(1)
    trie = depth_first_trie(*sys.argv[1:])
    print(trie.to_dot())
